package com.yolo.example.serverorless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.yolo.example.serverorless.services.logic.DocService;

import java.util.Date;
import java.util.Map;

/**
 * Created by mandrewes on 2/08/2018.
 */

@DynamoDBTable(tableName= DocService.TMP_TABLE_NAME)
public class DocDescriptor {
    private String id;
    private Date created;
    private Date modified;
    private String creator;
    private long contentLength;
    private String mimeType;
    private String fileName;
    private String visibilityFlag;
    private String groupId;
    private String accountId;
    private String customerId;
    private String documentUrl;
    private Map<String,String> freeFormMetadata;

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="created")
    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @DynamoDBAttribute(attributeName="modified")
    public Date getModified() {
        return modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }

    @DynamoDBAttribute(attributeName="creator")
    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    @DynamoDBAttribute(attributeName="contentLength")
    public long getContentLength() {
        return contentLength;
    }

    public void setContentLength(long contentLength) {
        this.contentLength = contentLength;
    }

    @DynamoDBAttribute(attributeName="mimeType")
    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    @DynamoDBAttribute(attributeName="fileName")
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @DynamoDBAttribute(attributeName="visibilityFlag")
    public String getVisibilityFlag() {
        return visibilityFlag;
    }

    public void setVisibilityFlag(String visibilityFlag) {
        this.visibilityFlag = visibilityFlag;
    }

    @DynamoDBAttribute(attributeName="groupId")
    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @DynamoDBAttribute(attributeName="accountId")
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    @DynamoDBAttribute(attributeName="customerId")
    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @DynamoDBAttribute(attributeName="documentUrl")
    public String getDocumentUrl() {
        return documentUrl;
    }

    public void setDocumentUrl(String documentUrl) {
        this.documentUrl = documentUrl;
    }

    @DynamoDBAttribute(attributeName="freeFormMeta")
    public Map<String, String> getFreeFormMetadata() {
        return freeFormMetadata;
    }

    public void setFreeFormMetadata(Map<String, String> freeFormMetadata) {
        this.freeFormMetadata = freeFormMetadata;
    }
}
